### ISSUE TITLE
Правки дро ДЗ 22

### ISSUE THREAD

**Issue by Dexter19** [Yura33-dev/yura33-dev#1]
// TASK 7
Тут нам треба використати цикл for:
const containers = document.getElementsByClassName('container');

for (let i = 0; i < containers.length; i++) {
    console.log(containers[i].firstElementChild.firstElementChild.outerHTML); 
}
---------------------------------------------------------------------

**Comment by Yura33-dev** [comment]
Доброго вечора. Поясніть, будь ласка, в чому різниця в даному випадку між loop for & for of? Я так розумію, працює так і так?

**Comment by Dexter19** [comment]
> Доброго вечора. Поясніть, будь ласка, в чому різниця в даному випадку між loop for & for of? Я так розумію, працює так і так?

В даному випадку у нас в задачі треба використовувати цикл for. А працює воно однаково для таких задач.Зазвичай цикл for є трохи швидшим, оскільки не виконує додаткових операцій, таких як виклики ітератора
